function AFCp = ARCloadFileBVAMS(subjNum,blockNum,dataPath)

% THIS FUNCTION LOADS DATA FROM THE BVAMS (.mat FILES)--EVERYTHING THAT
% HAPPENS HERE IS SPECIFIC TO THE NAMING AND ORGANIZATION CONVENTIONS OF
% THE DATA

% INITIALIZE SOMETHING TO RETURN EVEN IF NOTHING IS FOUND
AFCp = []; 

dataFolder = fullfile(dataPath,'data','stimulusData');

% LOAD 'MASTER FILE' SHOWING ALL FILE NAMES FOR EACH BLOCK AND CONDITION
load(fullfile(dataFolder,'AFCflsR'));

% FIND THE FILE NAME FOR THE BLOCK AND CONDITION IN QUESTION
filenameTmp = AFCfls{subjNum,blockNum};

% GRAB THE PART OF THE FILE NAME THAT DOESN'T INCLUDE THE PATH ON THE BVAMS
% LOCAL MACHINE
filenameTmp = filenameTmp((length('H:\Shared drives\CIVO_BVAMS\data\ARC\')+1):end);

load(fullfile(dataFolder,filenameTmp));

end